#!/usr/bin/env python3
"""
Extract exact sequences from matches.tsv generated by StrobeMap.

This script reads a matches.tsv file (output from StrobeMap) and the corresponding
reference and query FASTA files, then outputs the matched sequences on both
reference and query sides.

Usage:
    python extract_match_sequences.py matches.tsv reference.fasta query.fasta [output.tsv]

Output format (tab-separated):
    query_accession  ref_accession  ref_pos  query_pos  match_length  score  ref_sequence  query_sequence
    
    where score is the number of identical base pairs between ref_sequence and query_sequence
"""

import sys
from collections import OrderedDict


def parse_fasta(filepath):
    """
    Parse a FASTA or FASTQ file and return a dictionary mapping accession to sequence.

    :param filepath: path to FASTA or FASTQ file
    :returns: OrderedDict with accession as key and sequence as value
    """
    sequences = OrderedDict()
    current_acc = None
    current_seq = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            # Handle both FASTA (>) and FASTQ (@) headers
            if line.startswith('>') or line.startswith('@'):
                if current_acc is not None:
                    sequences[current_acc] = ''.join(current_seq)
                # Extract accession (first word after '>' or '@')
                current_acc = line[1:].split()[0]
                current_seq = []
            elif not line.startswith('+'):  # Skip FASTQ quality header
                current_seq.append(line)

        # Don't forget the last sequence
        if current_acc is not None:
            sequences[current_acc] = ''.join(current_seq)

    return sequences


def parse_matches(matches_file):
    """
    Parse matches.tsv file from StrobeMap output.
    
    :param matches_file: path to matches.tsv
    :yields: tuples of (query_acc, ref_acc, ref_pos, query_pos, match_length)
             Note: positions are 0-based in the output
    """
    current_query = None
    
    with open(matches_file, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            if line.startswith('>'):
                # Query accession line: "> query_acc" or "> query_acc Forward/Reverse"
                current_query = line[1:].strip().split()[0]
            else:
                # Match line: ref_acc  ref_pos  query_pos  match_length
                parts = line.split()
                if len(parts) >= 4:
                    ref_acc = parts[0]
                    ref_pos = int(parts[1]) - 1  # Convert to 0-based
                    query_pos = int(parts[2]) - 1  # Convert to 0-based
                    match_length = int(parts[3])
                    yield current_query, ref_acc, ref_pos, query_pos, match_length


def calculate_match_score(ref_seq, query_seq):
    """
    Calculate the number of matching base pairs between two sequences.

    :param ref_seq: reference sequence
    :param query_seq: query sequence
    :returns: number of positions where bases are identical
    """
    if len(ref_seq) != len(query_seq):
        # If lengths differ, compare up to the shorter length
        min_len = min(len(ref_seq), len(query_seq))
        ref_seq = ref_seq[:min_len]
        query_seq = query_seq[:min_len]
    
    return sum(1 for r, q in zip(ref_seq, query_seq) if r == q)


def extract_sequences(matches_file, ref_fasta, query_fasta, output_file=None):
    """
    Extract sequences for each match from reference and query FASTA files.

    :param matches_file: path to matches.tsv
    :param ref_fasta: path to reference FASTA
    :param query_fasta: path to query FASTA
    :param output_file: optional path to output file (prints to stdout if None)
    """
    # Parse FASTA files
    print(f"Loading reference sequences from {ref_fasta}...", file=sys.stderr)
    ref_seqs = parse_fasta(ref_fasta)
    print(f"  Loaded {len(ref_seqs)} reference sequences", file=sys.stderr)

    print(f"Loading query sequences from {query_fasta}...", file=sys.stderr)
    query_seqs = parse_fasta(query_fasta)
    print(f"  Loaded {len(query_seqs)} query sequences", file=sys.stderr)

    # Open output file or use stdout
    out = open(output_file, 'w') if output_file else sys.stdout

    # Write header
    out.write("query_accession\tref_accession\tref_pos\tquery_pos\tmatch_length\tscore\tref_sequence\tquery_sequence\n")
    
    # Process matches
    processed = 0
    errors = 0
    
    for query_acc, ref_acc, ref_pos, query_pos, match_length in parse_matches(matches_file):
        # Extract sequences
        ref_seq = None
        query_seq = None
        
        # Get reference sequence
        if ref_acc in ref_seqs:
            ref_full = ref_seqs[ref_acc]
            ref_end = ref_pos + match_length
            if ref_pos < 0:
                print(f"Warning: Invalid negative reference position for {ref_acc} "
                      f"(pos={ref_pos}, len={match_length})", file=sys.stderr)
                continue
            if ref_end <= len(ref_full):
                ref_seq = ref_full[ref_pos:ref_end]
            else:
                print(f"Warning: Match extends beyond reference sequence {ref_acc} "
                      f"(pos={ref_pos}, len={match_length}, seq_len={len(ref_full)})", file=sys.stderr)
                ref_seq = ref_full[ref_pos:] if ref_pos < len(ref_full) else 'N' * match_length
        else:
            print(f"Warning: Reference accession '{ref_acc}' not found in {ref_fasta}", file=sys.stderr)
            errors += 1
            continue
        
        # Get query sequence
        if query_acc in query_seqs:
            query_full = query_seqs[query_acc]
            
            # Skip invalid matches (negative position)
            if query_pos < 0:
                print(f"Warning: Invalid negative query position for {query_acc} "
                      f"(pos={query_pos}, len={match_length})", file=sys.stderr)
                continue
            
            # For short reads, the match_length from StrobeMap is often the reference span
            # which can be much larger than the actual query read length.
            # Extract only what's actually available from the query.
            actual_query_length = len(query_full) - query_pos
            
            if actual_query_length <= 0:
                print(f"Warning: Query position beyond sequence {query_acc} "
                      f"(pos={query_pos}, seq_len={len(query_full)})", file=sys.stderr)
                continue
            
            # Use the minimum of reference and query available lengths
            actual_length = min(match_length, actual_query_length)
            
            # Also limit reference sequence to match
            if ref_pos + actual_length > len(ref_full):
                actual_length = len(ref_full) - ref_pos
            
            query_seq = query_full[query_pos:query_pos + actual_length]
            ref_seq = ref_full[ref_pos:ref_pos + actual_length]
        else:
            print(f"Warning: Query accession '{query_acc}' not found in {query_fasta}", file=sys.stderr)
            errors += 1
            continue
        
        # Write output
        if ref_seq and query_seq:
            score = calculate_match_score(ref_seq, query_seq)
            out.write(f"{query_acc}\t{ref_acc}\t{ref_pos + 1}\t{query_pos + 1}\t"
                     f"{match_length}\t{score}\t{ref_seq}\t{query_seq}\n")
            processed += 1
    
    if output_file:
        out.close()
    
    print(f"\nProcessed {processed} matches successfully", file=sys.stderr)
    if errors > 0:
        print(f"Skipped {errors} matches due to missing sequences", file=sys.stderr)
    if output_file:
        print(f"Output written to {output_file}", file=sys.stderr)


def main():
    if len(sys.argv) < 4:
        print(__doc__)
        print("Arguments:")
        print("  matches.tsv      - StrobeMap output file")
        print("  reference.fasta  - Reference FASTA file")
        print("  query.fasta      - Query FASTA file")
        print("  output.tsv       - Optional output file (default: stdout)")
        sys.exit(1)
    
    matches_file = sys.argv[1]
    ref_fasta = sys.argv[2]
    query_fasta = sys.argv[3]
    output_file = sys.argv[4] if len(sys.argv) > 4 else None
    
    extract_sequences(matches_file, ref_fasta, query_fasta, output_file)


if __name__ == "__main__":
    main()
